### PR TITLE
Use Eclipse 2020-09 with MTA 5.0.1

### PR DESCRIPTION
**Pull request by RichardHoch**
Resolves https://issues.redhat.com/browse/WINDUP-2762

### CODE REVIEW

**Comment by PhilipCattanach** [comment]
@RichardHoch - That change is great please merge it to master and publish the Guide. Thanks, Phil

**Comment by RichardHoch** [comment]
@apinnick Please review. I switched the status of this PR from Draft PR to PR following Phil's review.

**Comment by apinnick** [comment]
Now that Eclipse 2020-06 is no longer the current version, I think you should also remove the line from the Known Issues about MTA working with CodeReady Studio. You can just keep the line about Eclipse 2020-06 and null pointer exception. Please add the change to this PR.

**Comment by RichardHoch** [comment]
@apinnick : line about CodeReady Studio removed from Known Issues entry. Please review.

**Pull request merged**
