### PR TITLE
MTA-139: Download HTML and CSV analysis reports

### PR DESCRIPTION
**Pull request by sbeskin-redhat**
Resolves: https://issues.redhat.com/browse/MTA-139
MTA 6.1.0
Preview: https://deploy-preview-672--windup-documentation.netlify.app/docs/web-console-guide/master/index.html#mta-web-downloading-an-analysis-report_user-interface-guide

### CODE REVIEW

**Review by abrugaro — APPROVED** [review]
Looks good!

**Comment by anarnold97** [comment]
@rromannissen & @dymurray - copying you in on the MTA 6.1.0 PRs.
Please can I ask for your comments?
Thanks

**Comment by anarnold97** [comment]
@rromannissen & @dymurray - copying you in on the MTA 6.1.0 PRs.
Please can I ask for your comments?
Thanks

**Comment by RichardHoch** [comment]
LGTM!

**Pull request merged**
