### PR TITLE
Windup 3703 new option skipSourceCodeReports hvider

### PR DESCRIPTION
**Pull request by HagayVider1**
@anarnold97 

Windup-3703: https://issues.redhat.com/browse/WINDUP-3703

Added skipSourceCodeReports option to files:
cli-args.adoc
web-create-project.adoc

### CODE REVIEW

**Comment by anarnold97** [comment]
@HagayVider1 
There are merge conflicts with this PR.

Please can you check the files you included in the PR, should all of these files be included?

**Comment by anarnold97** [comment]
@HagayVider1 - please can you remind me to discuss this PR with you

**Comment by anarnold97** [comment]
@HagayVider1 - fixed merge conflicts.

**Comment by PhilipCattanach** [comment]
The changes look fine to me. can we get this change merged and published.

**Comment by anarnold97** [comment]
@PhilipCattanach - apologies for missing it. Merged and published

**Comment by stillalearner** [comment]
lgtm.

**Comment by anarnold97** [comment]
@stillalearner thanks very much for your help

**Pull request merged**
