### PR TITLE
WINDUP-3694: MTR1.1.0-attributes update

### PR DESCRIPTION
**Pull request by anarnold97**
[WINDUP-3694](https://issues.redhat.com/browse/WINDUP-3694): MTR1.1.0-attributes update.

changes made to `document-attributes.adoc` lines 35 to 54

```
ifdef::mtr[]
    > :ProductName: Migration Toolkit for Runtimes
    > :DocInfoProductName: Migration Toolkit for Runtimes
    > :DocInfoProductNumber: 1.1
    > :ProductShortName: MTR
    > :LC_PSN: mtr
    > :DocInfoProductNameURL: migration_toolkit_for_runtimes
    > :WebName: web console
    > :WebNameTitle: Web Console
    > :WebNameURL: web_console_guide
    > :WebConsoleBookName: {WebNameTitle} Guide
    > :ProductVersion: 1.1.0
    > :PluginName: MTR plugin
    > :ProductDistributionVersion: 1.1.0.GA-redhat-00003
    > :ProductDistribution: mtr-1.1.0.GA-offline
    > :DevDownloadPageURL: https://developers.redhat.com/products/mtr/download
    > :IDEPluginFilename: migrationtoolkit-mtr-eclipse-plugin-repository
    > :JiraWindupURL: https://issues.redhat.com/projects/WINDUP
    :CodeReadyStudioDownloadPageURL: http://download.jboss.org/jbosstools/photon/stable/updates/mtr/
endif::[]
```

### CODE REVIEW

**Comment by PhilipCattanach** [comment]
I believe the values above to be correct.

**Comment by anarnold97** [comment]
I am going to merge this and publish to stage
If there are any edits from QE, I will make them before publishing to the public portal

**Review by stillalearner — COMMENTED** [review]
lgtm

**Comment by sbeskin-redhat** [comment]
@anarnold97 
Looks OK

**Pull request merged**
