### PR TITLE
WINDUP-3946: release notes for MTR 1.1.1 cgo release

### PR DESCRIPTION
**Pull request by anarnold97**
[WINDUP-3946](https://issues.redhat.com/browse/WINDUP-3946)

Release Notes for MTR 1.1.1

Adding release notes to cover CGO only release

Direct preview - https://deploy-preview-709--windup-documentation.netlify.app/docs/release-notes-mtr/master/index.html#mtr-rn-resolved-issues-111_release-notes

### CODE REVIEW

**Comment by anarnold97** [comment]
@PhilipCattanach - please can I check that you are ok with the following for MTR 1.1.1 release notes? Or do you want a link including to an explanation of the CGO release (if there is one)?
Thanks

**Comment by PhilipCattanach** [comment]
Hi @anarnold97 
I would add a one sentence:
This release contains a number of [bug fixes](https://issues.redhat.com/issues/?filter=12403083) and an upgrade to the container images.

**Comment by anarnold97** [comment]
- Changed the filter for resolved issues to <project in (WINDUP, WINDUPRULE) AND status in (Verified, "Release Pending", Closed) AND issuetype = Bug AND fixVersion in (MTR-1.1.1) ORDER BY component DESC>. I was not sure <project in (WINDUP, WINDUPRULE) AND status in (Verified, "Release Pending", Closed) AND issuetype = Bug AND fixVersion in (MTR-1.0.0, MTA-6.0.0) ORDER BY component DESC>

- Added the resolved issues page to keep the formatting the same as previous releases

- Changed the wording in the CGO statement

**Comment by PhilipCattanach** [comment]
Thanks Andy, Your filter provides the same list of fixed bugs

**Comment by anarnold97** [comment]
@PhilipCattanach - cool. thanks for checking
you good for me to publish, please?

**Pull request merged**
