### PR TITLE
Transaction analysis MAVIN

### PR DESCRIPTION
**Pull request by CarmiWisemon**
MTR 1.0 
Resolves https://issues.redhat.com/browse/WINDUP-3387?filter=-3 preview

https://deploy-preview-542--windup-documentation.netlify.app/docs/maven-guide/master/index.html#maven-arguments_maven-guide

The update is in Appendix A: Reference material Table A1, Argument (enableTransactionAnalysis)

### CODE REVIEW

**Comment by RichardHoch** [comment]
@CarmiWisemon -- LGTM; you can (and should) rewove the Draft status of this PR and also remove "WIP" from its title.

**Comment by PhilipCattanach** [comment]
@CarmiWisemon - The changes look good to me. Thanks

**Review by sshveta — APPROVED** [review]
LGTM

**Review by stillalearner — APPROVED** [review]
lgtm

**Pull request merged**
