### PR TITLE
MTA repo cleanup:folders and .adocs

### PR DESCRIPTION
**Pull request by RichardHoch**
Phase I of cleaning up the MTA repo. This phase includes:
* Labeling and moving all version 4 folders and .adoc files into the "legacy" section of the repo
* removing any .adoc files from the topics_5 folder that do not apply to any version 5 documents
Phase II will include removing images that are not included in any version 5 documents.

### CODE REVIEW

**Comment by RichardHoch** [comment]
@apinnick: please review.

**Comment by apinnick** [comment]
Remove "_5" from all the folder names.
Recommend moving the RN folders for the 5.x versions into a single folder called Release Notes. I can update Pantheon to look for the subfolders.

**Comment by RichardHoch** [comment]
@apinnick: changes made.

**Comment by RichardHoch** [comment]
@apinnick  IDs removed; other changes made. Identifying which images should be deleted is going to take time, so I am doing it on a separate PR.

**Comment by apinnick** [comment]
Is this ready for merge? If so, squash the commits. Thanks

**Comment by RichardHoch** [comment]
@apinnick: ready for merge.

**Comment by apinnick** [comment]
You have merge conflicts

**Comment by RichardHoch** [comment]
@apinnick Fixed them.

**Pull request merged**
