### PR TITLE
mta operator installation on openshift

### PR DESCRIPTION
**Pull request by apinnick**
https://issues.redhat.com/browse/WINDUP-2784

Preview build: http://file.tlv.redhat.com/~apinnick/mta-operator_web-console-guide_5/#installing_the_web_console_on_red_hat_openshift_container_platform

### CODE REVIEW

**Comment by PhilipCattanach** [comment]
Thanks Avital - that reads really well and describes the process perfectly. Spot on.

**Comment by apinnick** [comment]
> Do you think it would be useful to add a line about changing the fields values provided ?

Please comment on the files themselves. I can't tell what you are referring to if you add a comment to the PR.

**Comment by apinnick** [comment]
> In fact the operator can be installed in any user created namespace , so probably not forcing `mta` as the value would help on that.... only mentioning that the namespace needs to be created beforehand.
> 
> What do you think on changing this ?

No, not necessary to change. It says "for example, `mta`," which indicates to the user that `mta` is being used in the procedure as an example but it can be anything. The procedure does not force the user to create a namespace called `mta`.

**Comment by apinnick** [comment]
> It's not mandatory to use the "Developer" perspective, it can also be done using the "Administrator" perspective.
> 
> What do you think about providing instructions on doing the same on both perspectives

I don't know what you are referring to. Please comment on the lines in the files

**Pull request merged**
