### PR TITLE
MTA-451 Adding a section for Eviction threshold

### PR DESCRIPTION
**Pull request by anarnold97**
[MTA-451](https://issues.redhat.com/browse/MTA-451)

PR submitted on behalf of @HagayVider1, who wants to add a subsection for Eviction threshold

### CODE REVIEW

**Comment by anarnold97** [comment]
@rromannissen & @dymurray please can I ask you to have a look at this PR, which I copied from Hagay's PR, which has junk files in it.

**Review by dymurray — APPROVED** [review]
LGTM

**Review by abrugaro — APPROVED** [review]
LGTM

**Comment by jmontleon** [comment]
Sorry for not commenting sooner, I missed earlier notifications and only just saw the notification for merge.

I just want to note I am generally in favor of this documentation and it matches the OpenShift documentation. I opened https://issues.redhat.com/browse/OCPNODE-1579 though because in my testing the behavior did not match the documentation. Unfortunately it still has not received any feedback.

**Pull request merged**
